### ISSUE TITLE
Publish new release to PyPi?

### ISSUE THREAD

**Issue by Guts** [baryonyx5/click-keyring#4]
Hi @baryonyx5,

Would it be possible to publish a new version on PyPi please?
I need to publish a package using my latest modifications and my end-user doesn't like the download from GitHub.

Thanks!

**Comment by baryonyx5** [comment]
Sorry for the delay. Version 0.2.0 should be available on pypi now.

**Comment by Guts** [comment]
Thank you! If you are interested in using GitHub Actions, it's easy to set up a workflow to deploy to Pypi on a git tag (or wathever).

**Comment by baryonyx5** [comment]
Yes, I am interested and plan to pursue that with some of my time off this month. The primary reason I published this to pypi was as a learning exercise for packaging and deployment workflows so I appreciate the feedback and suggestions.
